const cases = {
"HA": "U R D' R' U2 R D R' U2' U'",
"HB": "R D' R' U' R D R' U",
"HD": "U2 R D' R' U R D R' U' U2'",
"HE": "R D' U R D R' U' R D' R' D R'",
"HF": "L2 U' R' U L2' U' R U",
"HG": "L2 U' R' U L U' R U L' L2'",
"HI": "R U' D R' D R U2 R' D' R U2' D' U R'",
"HK": "U R U' R D' R' U' R D R' U U R' U'",
"HL": "D2 R U R' D' R U' R' D D2'",
"HN": "U R R D' R' U2 R D R' U2' R' U'",
"HO": "R D' R' U' R D2 R' U R D2' D R'",
"HP": "D2 R U R' D2' R U' R'",
"HQ": "U' L U R U' L' U R'",
"HR": "U2 R2 D' R' U R D R' U' R R2' U2'",
"HT": "D2 R U R' D R U' R' D' D2'",
"HU": "D' R D U' R' U R D2 R' U' R D2' U D' R' D",
"HV": "D R2 U L' U' R2' U L U' D'",
"HW": "D L D' R2 D L' D' R2'",
"BA": "R' B' R U' R D R' U R D' R' R' B R",
"BD": "l D R' D' R U R' D R U' D' l'",
"BE": "R U R D R' U' R D' R' R'",
"BF": "R' R' D' R U' R' D R U R",
"BG": "R' D R U R' D' R U'",
"BI": "R U2 R D R' U2' R D' R' R'",
"BK": "D' R' D R U R' D' R U' D",
"BL": "D R' D' R U R' D R U' D'",
"BO": "U' R D R' U R D' R'",
"BP": "R' D' R U R' D R U'",
"BR": "R' R' D' R U2 R' D R U2' R",
"BS": "D' U' R D R' U R D' R' D",
"BT": "D U' R D' R' U R D R' D'",
"BU": "R F' R' U' R D R' U R D' F R'",
"BV": "U' R' D R R D' R' U R D R' U' R' D' R U",
"BW": "U R D' R' U' R' D R U R' D' R R D R' U'",
"BX": "l' D R' D' R U R' D R U' D' l",
};

module.exports = cases;
